# Generated by Django 2.2 on 2020-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200624_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Biography', 'Biography'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Self-Help', 'Self-Help'), ('Thriller', 'Thriller')], max_length=20, unique=True),
        ),
    ]
