# Generated by Django 2.2 on 2020-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200624_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
