# Generated by Django 2.2 on 2020-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200624_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
