# Generated by Django 2.2 on 2020-07-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200624_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='name',
            field=models.TextField(default='test'),
        ),
    ]
