# Generated by Django 2.2 on 2020-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_libraryuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='name',
            field=models.TextField(),
        ),
    ]
