# Generated by Django 2.2 on 2020-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200809_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
